Fix Mutation Issues
upstage-org/mobilise pull request #158
Opened 2021-03-01 15:04 UTC by nguyenhongphat0

Separated issue for fixing mutations

2021-03-01 15:22 UTC, paul-rohrlach approved these changes

2021-03-01 15:25 UTC, paul-rohrlach commented
@gloriajw would you mind checking this too?  I'm fine with the changes in general, but I can't remember whether there was a particular reason we didn't use `with` scoping from the outset?

2021-03-01 15:29 UTC, gloriajw reviewed
This is a valid correction: 
with ScopedSession() as local_db_session:
But this is not:
@jwt_required()
This has to be: @jwt_required

2021-03-01 15:35 UTC, paul-rohrlach requested changes

2021-03-01 15:35 UTC, paul-rohrlach commented on user/schema.py
> +    @jwt_required()
Please revert this particular change

2021-03-01 15:45 UTC, nguyenhongphat0 commented
I got `"wrapper() got an unexpected keyword argument 'inbound'"` on updateUser mutation when these parentheses are missing, Paul 🤔 
<img width="1342" alt="Screenshot 2021-03-01 at 22 44 32" src="https://user-images.githubusercontent.com/29925961/109521253-b3563880-7adf-11eb-917f-2d6ce8a59fe5.png">

2021-03-01 15:47 UTC, paul-rohrlach commented
That's interesting...

@gloriajw have you come across this before?

2021-03-01 15:54 UTC, gloriajw commented
No, but looking now...

2021-03-01 15:55 UTC, nguyenhongphat0 commented
I don't know why but adding these parentheses make the error gone away

<img width="1344" alt="Screenshot 2021-03-01 at 22 52 22" src="https://user-images.githubusercontent.com/29925961/109522474-e3eaa200-7ae0-11eb-800c-4743d93f38d5.png">

2021-03-01 16:00 UTC, gloriajw commented
But the problem is, parens invoke the decorator immediately, which is not what you want. Without parens it's a function factory, which is what you want in a decorator. 
This looks correct, I have to dig a bit and see why this isn't working:
def jwt_required(fn):
    """
    Overriding built-in decorator, to catch the exception
    thrown when signature expires.
    """
    @wraps(fn)
    def wrapper(*args, **kwargs):

2021-03-02 01:01 UTC, paul-rohrlach approved these changes

2021-03-02 01:01 UTC, merged

2021-03-02 01:05 UTC, gloriajw commented
Phat was right! @jwt_required()