update user manual
upstage-org/mobilise pull request #300
Opened 2021-05-03 11:25 UTC by elisadcg

2021-05-05 16:19 UTC, paul-rohrlach requested changes

2021-05-05 16:19 UTC, paul-rohrlach commented on docs/user_manual.rst
> +introduction bla bla bla
Can we either finish this sentence with something (instead of blah blah blah) or remove it for now?

2021-05-05 17:48 UTC, CBeez23 commented
I will write an introduction ASAP and remove the "blah blah blah". I'm going to go over the whole document today proofreading and adding necessary sections.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Paul Rohrlach ***@***.***>
Sent: Wednesday, May 5, 2021 11:20:06 AM
To: upstage-org/mobilise ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [upstage-org/mobilise] update user manual (#300)


@paul-rohrlach requested changes on this pull request.

________________________________

In docs/user_manual.rst<https://github.com/upstage-org/mobilise/pull/300#discussion_r626712874>:

> @@ -177,8 +177,35 @@ Performing (as an artist player)
 *******************************************************
 A performance involves several types of media uploads: avatars, props, and backgrounds. You chose these when you set the stage, and during a live performance they interact with each other in view of the audience. The players each control an avatar that may interact with other avatars, props, and the audience in front of a background. If the stage's creator chose music or sound effects, those media files will play.

+Settings of the Stage
+------------------------
+introduction bla bla bla


Can we either finish this sentence with something (instead of blah blah blah) or remove it for now?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://github.com/upstage-org/mobilise/pull/300#pullrequestreview-652505508>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AMD7DAS4FTC7PSNWM24XN2DTMFV3NANCNFSM44AUTYMQ>.

2021-05-05 18:52 UTC, vickis commented
Good work Team

We refer to backgrounds as backdrops (its a theatre thing:)
Also the audio needs to be activated to play (so the sentence could say ..:
can rather than will be played

Don’t forget there is also text and drawing and the chat window are also
all part of a performance :)



On Thursday, May 6, 2021, CBeez23 ***@***.***> wrote:

> I will write an introduction ASAP and remove the "blah blah blah". I'm
> going to go over the whole document today proofreading and adding necessary
> sections.
>
> Get Outlook for Android<https://aka.ms/ghei36>
>
> ________________________________
> From: Paul Rohrlach ***@***.***>
> Sent: Wednesday, May 5, 2021 11:20:06 AM
> To: upstage-org/mobilise ***@***.***>
> Cc: Subscribed ***@***.***>
> Subject: Re: [upstage-org/mobilise] update user manual (#300)
>
>
> @paul-rohrlach requested changes on this pull request.
>
> ________________________________
>
> In docs/user_manual.rst<https://github.com/upstage-org/
> mobilise/pull/300#discussion_r626712874>:
>
> > @@ -177,8 +177,35 @@ Performing (as an artist player)
> *******************************************************
> A performance involves several types of media uploads: avatars, props, and
> backgrounds. You chose these when you set the stage, and during a live
> performance they interact with each other in view of the audience. The
> players each control an avatar that may interact with other avatars, props,
> and the audience in front of a background. If the stage's creator chose
> music or sound effects, those media files will play.
>
> +Settings of the Stage
> +------------------------
> +introduction bla bla bla
>
>
> Can we either finish this sentence with something (instead of blah blah
> blah) or remove it for now?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub<https://github.com/
> upstage-org/mobilise/pull/300#pullrequestreview-652505508>, or
> unsubscribe<https://github.com/notifications/unsubscribe-auth/
> AMD7DAS4FTC7PSNWM24XN2DTMFV3NANCNFSM44AUTYMQ>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/upstage-org/mobilise/pull/300#issuecomment-832887209>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABANO2X4WDZGKTILJSCLI5LTMGAJ3ANCNFSM44AUTYMQ>
> .
>

2021-05-05 20:00 UTC, helenvarley commented
yes great work! i'm sorry i haven't been able to contribute recently - with the workshops & travelling it's all been full-on, & now i have a week of extreme busy-ness with my other big project. next week i should have more time ... ("should" ... :laughing:

2021-05-12 16:43 UTC, paul-rohrlach commented
Do we have any progress on this @elisadcg and @CBeez23 ?

2021-05-13 23:05 UTC, closed without merging

2021-05-14 11:54 UTC, helenvarley commented
elisa has given this link:  https://github.com/upstage-org/mobilise/blob/elisadcg-patch-12/docs/user_manual.rst
& my mission for this afternoon is to start looking at it & working on the english ... :)

2021-05-14 20:06 UTC, CBeez23 commented
I can help this evening. I've been meaning to. I'm sorry I didn't get to it before.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Helen Varley Jamieson ***@***.***>
Sent: Friday, May 14, 2021 6:54:49 AM
To: upstage-org/mobilise ***@***.***>
Cc: CBeez23 ***@***.***>; Mention ***@***.***>
Subject: Re: [upstage-org/mobilise] update user manual (#300)


elisa has given this link: https://github.com/upstage-org/mobilise/blob/elisadcg-patch-12/docs/user_manual.rst
& my mission for this afternoon is to start looking at it & working on the english ... :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/upstage-org/mobilise/pull/300#issuecomment-841196936>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AMD7DAV2J4BN5FZSJXZ5XE3TNUFQTANCNFSM44AUTYMQ>.

2021-05-15 10:18 UTC, helenvarley commented
great, thanks @CBeez23 :smiley: i got as far as the Media section yesterday, & will carry on when i have time over the weekend. 
please check things against https://dev-app1.upstage.org.nz/V4.0/ui/ - as this is where the latest changes are. there are still some things in the rst files that are from the previous version so need to be updated, e.g. some of the terminology & workflows have been improved.